[general]
import = [
  "~/.config/alacritty/alabaster-dark.toml"
]

[window]
dimensions = { columns = 80, lines = 24 }
title = "Terminal"
option_as_alt = "Both" # passes through option key to the terminal; necessary for zellij!
decorations = "Full"
padding = { x = 3, y = 5 }
dynamic_padding = true

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

[font]
size = 12
normal = { family = "Hack Nerd Font Mono", style = "Regular" }

# Keybindings because why not
[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "0"
mods = "Control"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "n"
mods = "Control"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "n"
mods = "Command"
