# TokyoNight Alacritty Colors
#colors:
  # Default colors
  #  primary:
  #    background: '#2E3440'
  #    foreground: '#D8DEE9'
  #
  #  # Normal colors
  #  normal:
  #    black: '#3B4252'
  #    red: '#BF616A'
  #    green: '#A3BE8C'
  #    yellow: '#EBCB8B'
  #    blue: '#81A1C1'
  #    magenta: '#B48EAD'
  #    cyan: '#88C0D0'
  #    white: '#E5E9F0'
  #
  #  # Bright colors
  #  bright:
  #    black: '#4C566A'
  #    red: '#BF616A'
  #    green: '#A3BE8C'
  #    yellow: '#EBCB8B'
  #    blue: '#81A1C1'
  #    magenta: '#B48EAD'
  #    cyan: '#8FBCBB'
  #    white: '#ECEFF4'

# Colors (Nord)
colors:
   # Default colors
   primary:
     background: '#2E3440'
     foreground: '#D8DEE9'

   # Normal colors
   normal:
     black:   '#3B4252'
     red:     '#BF616A'
     green:   '#A3BE8C'
     yellow:  '#EBCB8B'
     blue:    '#81A1C1'
     magenta: '#B48EAD'
     cyan:    '#88C0D0'
     white:   '#E5E9F0'

   # Bright colors
   bright:
     black:   '#4C566A'
     red:     '#BF616A'
     green:   '#A3BE8C'
     yellow:  '#EBCB8B'
     blue:    '#81A1C1'
     magenta: '#B48EAD'
     cyan:    '#8FBCBB'
     white:   '#ECEFF4'

env:
  TERM: 'xterm-256color-italic'

font:
  size: 12.0
  normal:
    family: FiraCode Nerd Font 
    style: Regular

  bold:
    family: FiraCode Nerd Font
    style: Bold

  italic:
    family: FiraCode Nerd Font
    style: Italic


key_bindings:
  - {
      key: N,
      mods: Command,
      command:
        {
          program: "open",
          args: [ "-n", "/Applications/Alacritty.app" ]
        }
    }

window:
  dynamic_title: true
  decorations: transparent
  padding:
    x: 25
    y: 40

      #shell:
      #  program: /usr/local/bin/tmux # <- set this to the path of your tmux installation
      #  args:
      #    - new-session
      #    - -A
      #    - -D
      #    - -s
      #    - main
