"installs vim-plug
let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')

Plug 'vim-airline/vim-airline'
"Plug 'wojciechkepka/vim-github-dark'
Plug 'arcticicestudio/nord-vim'
"Plug 'ghifarit53/tokyonight-vim'
Plug 'scrooloose/nerdtree'

call plug#end()

set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'godlygeek/tabular'
Plugin 'plasticboy/vim-markdown'
"Plugin 'Valloric/YouCompleteMe'

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" YouCompleteMe
let g:ycm_global_ycm_extra_conf='~/.vim/bundle/YouCompleteMe/.ycm_extra_conf.py'
let g:ycm_confirm_extra_conf=0
let g:ycm_python_binary_path='/usr/bin/python3'

set nocompatible
if (has("termguicolors"))
  set termguicolors
endif

"let g:tokyonight_style = 'storm' " available: night, storm
"let g:tokyonight_enable_italic = 0
syntax enable
colorscheme nord

set tabstop=4
set number
set relativenumber

autocmd FileType python map <F5> <Esc>:w<CR>:!clear;python %<CR>
autocmd FileType python imap <F5> <Esc>:w<CR>:!clear;python %<CR>

"enabling NERDTree on new editor
"autocmd VimEnter * NERDTree
"autocmd BufWinEnter * NERDTreeMirror

"autocmd VimEnter * wincmd w
