let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged/')

Plug 'tpope/vim-sensible'
Plug 'morhetz/gruvbox'

call plug#end()

set background=dark
colorscheme gruvbox

" Sane defaults
set number
set relativenumber
set mouse=a
set cursorline
set ignorecase
set smartcase
syntax on
filetype plugin on
